logging:
  level:
    ROOT: INFO
    org.oneworldaccuracy.demo: INFO

spring:
  application:
    name: one_world_accuracy
  profiles:
    active: #spring.profiles.active#
  liquibase:
    change-log: classpath:liquibase/master.xml
    contexts: prod
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/db_1wa
    username: postgres
    password: 0908gyvbkjw3456ydfgh9098
    hikari:
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate.jdbc.time_zone: UTC
    #      hibernate.id.new_generator_mappings: true
    #      hibernate.connection.provider_disables_autocommit: true
    #      hibernate.cache.use_second_level_cache: true
    #      hibernate.cache.use_query_cache: false
    #      hibernate.generate_statistics: false

    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
