logging:
  level:
    ROOT: DEBUG
    org.oneworldaccuracy.demo: DEBUG

spring:
  liquibase:
    contexts: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/dev_1wa_db
    username: postgres
    password: password
    hikari:
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
